"""Lightweight genetic-style alpha refinement utilities."""
from __future__ import annotations

import random
import re
from typing import Iterable, List, Optional, Sequence, Set

from backend.core.data_fields import BRAINDataFields, get_data_fields
from backend.core.expression_normalizer import normalize_brain_expression
from backend.generation.candidates import AlphaCandidate
from backend.generation.dedup import ExpressionDeduplicator


class GeneticAlphaRefiner:
    """Create mutations and crossovers from seed expressions."""

    WINDOW_VALUES = (5, 10, 20, 40, 60, 120, 252)
    GROUPS = ("sector", "industry", "subindustry", "market")
    FIELD_SWAPS = {
        "close": ("open", "vwap", "returns"),
        "open": ("close", "vwap"),
        "vwap": ("close", "open"),
        "volume": ("adv20", "adv5"),
        "adv20": ("volume", "adv5"),
        "returns": ("ret_0_1", "ret_1_5", "ret_5_20"),
    }
    OPERATOR_SWAPS = {
        "ts_rank": ("ts_zscore", "ts_decay_linear", "ts_mean"),
        "ts_mean": ("ts_decay_linear", "ts_rank"),
        "ts_zscore": ("ts_rank", "ts_std_dev"),
        "rank": ("zscore", "scale"),
    }

    def __init__(
        self,
        schema: Optional[BRAINDataFields] = None,
        seed: Optional[int] = None,
    ):
        self.schema = schema or get_data_fields()
        self.random = random.Random(seed)

    def refine(
        self,
        expressions: Sequence[str],
        count: int = 20,
        existing_expressions: Optional[Iterable[str]] = None,
    ) -> List[AlphaCandidate]:
        """Return unique mutated and crossed-over expressions."""
        count = max(1, min(count, 500))
        seed_expressions = [expr.strip() for expr in expressions if expr and expr.strip()]
        deduplicator = ExpressionDeduplicator(existing_expressions)
        for expression in seed_expressions:
            deduplicator.add(expression)

        candidates: List[AlphaCandidate] = []
        attempts = 0
        while len(candidates) < count and attempts < count * 30:
            attempts += 1
            if len(seed_expressions) >= 2 and self.random.random() < 0.30:
                expression = self.crossover(
                    self.random.choice(seed_expressions),
                    self.random.choice(seed_expressions),
                )
                strategy = "crossover"
            else:
                expression = self.mutate(self.random.choice(seed_expressions))
                strategy = "mutation"

            expression = normalize_brain_expression(expression)
            valid, _ = self.schema.validate_expression_basic(expression)
            if not valid:
                continue

            is_unique, _, _ = deduplicator.add(expression)
            if is_unique:
                candidates.append(
                    AlphaCandidate(
                        expression=expression,
                        strategy=strategy,
                        source_fields=tuple(sorted(self._extract_fields(expression))),
                        operators=tuple(sorted(self._extract_operators(expression))),
                        rationale="Generated by genetic-style refinement of seed expressions.",
                        score=0.62 if strategy == "mutation" else 0.66,
                    )
                )

        return candidates

    def mutate(self, expression: str) -> str:
        """Apply one random mutation to an expression."""
        mutation = self.random.choice(
            (
                self._mutate_window,
                self._swap_field,
                self._swap_operator,
                self._wrap_transform,
                self._group_neutralize,
            )
        )
        return mutation(expression)

    def crossover(self, left: str, right: str) -> str:
        """Combine two expressions with a simple arithmetic wrapper."""
        left = left.strip()
        right = right.strip()
        operator = self.random.choice(("+", "-", "*"))
        wrapper = self.random.choice(("rank", "scale", "zscore"))
        return f"{wrapper}(({left}) {operator} ({right}))"

    def _mutate_window(self, expression: str) -> str:
        numbers = re.findall(r"(?<=,\s)\d+(?=\))", expression)
        if not numbers:
            return expression
        old = self.random.choice(numbers)
        replacement = str(self.random.choice([value for value in self.WINDOW_VALUES if str(value) != old]))
        return re.sub(rf"(?<=,\s){old}(?=\))", replacement, expression, count=1)

    def _swap_field(self, expression: str) -> str:
        available_swaps = []
        for source, targets in self.FIELD_SWAPS.items():
            if re.search(rf"\b{source}\b", expression):
                valid_targets = [target for target in targets if self.schema.validate_field(target)]
                if valid_targets:
                    available_swaps.append((source, valid_targets))

        if not available_swaps:
            return expression

        source, targets = self.random.choice(available_swaps)
        target = self.random.choice(targets)
        return re.sub(rf"\b{source}\b", target, expression, count=1)

    def _swap_operator(self, expression: str) -> str:
        available_swaps = []
        for source, targets in self.OPERATOR_SWAPS.items():
            if re.search(rf"\b{source}\b", expression):
                available_swaps.append((source, targets))

        if not available_swaps:
            return expression

        source, targets = self.random.choice(available_swaps)
        target = self.random.choice(targets)
        return re.sub(rf"\b{source}\b", target, expression, count=1)

    def _wrap_transform(self, expression: str) -> str:
        wrapper = self.random.choice(("rank", "scale", "zscore"))
        if expression.strip().startswith(f"{wrapper}("):
            return expression
        return f"{wrapper}({expression})"

    def _group_neutralize(self, expression: str) -> str:
        if "group_neutralize" in expression:
            return expression
        group = self.random.choice(self.GROUPS)
        return f"group_neutralize({expression}, {group})"

    def _extract_fields(self, expression: str) -> Set[str]:
        tokens = set(re.findall(r"\b[a-zA-Z_][a-zA-Z0-9_]*\b", expression))
        return {token for token in tokens if self.schema.validate_field(token)}

    def _extract_operators(self, expression: str) -> Set[str]:
        tokens = set(re.findall(r"\b[a-zA-Z_][a-zA-Z0-9_]*\s*\(", expression))
        operators = {token.strip().rstrip("(") for token in tokens}
        return {operator for operator in operators if self.schema.validate_operator(operator)}
